spring:
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017
      database: jwt_security

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
      auto-offset-reset: earliest
    producer:
      acks: all

