scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'upload-application'
    static_configs:
      - targets: ['localhost:8080']